/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Sitting Talking.glb --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'mixamo.com'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Beta_Surface: THREE.Mesh
    Beta_Joints: THREE.Mesh
  }
  materials: {
    Beta_HighLimbsGeoSG3: THREE.MeshStandardMaterial
    Beta_Joints_MAT1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
 const { nodes, materials, animations } = useGLTF('/avatar.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh name="Beta_Surface" geometry={(nodes.Beta_Surface as THREE.Mesh).geometry} material={materials.Beta_HighLimbsGeoSG3} />
<mesh name="Beta_Joints" geometry={(nodes.Beta_Joints as THREE.Mesh).geometry} material={materials.Beta_Joints_MAT1} />
</group>
    </group>
  )
}

useGLTF.preload('/avatar.glb')
